version: '3.8'
services:
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:${MYSQL_PORT}/${MYSQL_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "${MYSQL_USER}",
        "spring.datasource.password" : "${MYSQL_PASSWORD}"
      }'
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:8.0.36
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}" ]
      retries: 10
      interval: 3s
      timeout: 30s
volumes:
  mysql-data: { }
