server:
  error:
    path: /error/
  port: ${SERVER_PORT}

spring:
  main:
    allow-circular-references: true
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${MYSQL_SHOW_SQL}
    open-in-view: 'false'
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    username: ${MYSQL_USER}
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}

logging:
  level:
    org:
      springframework:
        security: DEBUG
  pattern:
    console: '-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd''T''HH:mm:ss.SSSXXX}}){faint}
      %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr(${LOGGED_APPLICATION_NAME:-}[%15.15t]){faint}
      %clr(${LOG_CORRELATION_PATTERN:-}){faint}%clr(%-40.40logger{39}){cyan} %clr(:){faint}
      %clr(%replace(%X{logId}){''(.+)'',''#LogId: $1 '':-}){green} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}'

security:
  encoding-strength: ${SECURITY_ENCODING_STRENGTH}
